### PR TITLE
fix: build tests and docs only if main project

### PR DESCRIPTION
**Pull request by FrogTheFrog**
## Description
Build tests and docs only if main project. Also applied some fixes from libdisplaydevice.

Removed the `-ggdb` flag as I could not find it anywhere in the provided link...

## Type of Change
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Dependency update (updates to dependencies)
- [ ] Documentation update (changes to documentation)
- [ ] Repository update (changes to repository files, e.g. `.github/...`)

## Checklist
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added or updated the in code docstring/documentation-blocks for new or existing methods/components

### CODE REVIEW

**Comment by ReenigneArcher** [comment]
`-ggdb` was added here: https://github.com/LizardByte/Sunshine/pull/2512

Whether it's useful... I don't know.

**Comment by FrogTheFrog** [comment]
> `-ggdb` was added here: [LizardByte/Sunshine#2512](https://github.com/LizardByte/Sunshine/pull/2512)
> 
> Whether it's useful... I don't know.

Should we keep it?

**Comment by ReenigneArcher** [comment]
I think so... I incorporated it from your change in ldd. But in Sunshine we can't make the whole build a debug build, so only the tests are in debug.

Or for this library maybe need more of your other changes in ldd... probably for later.

**Comment by FrogTheFrog** [comment]
But you are already building both release and debug builds for Sunshine. Same for this one :thinking:

**Comment by ReenigneArcher** [comment]
Why are your PRs giving so much trouble with codecov? 🤔

**Pull request merged**
